pipeline {
    agent any

    parameters {
        choice(
            name: 'ACTION',
            choices: ['apply', 'destroy'],
            description: 'Select Terraform action'
        )
    }

    stages {
       stage('terraform checkout){
             steps {
               git branch: 'main', url: 'https://github.com/mahimapatel93/Terraform_Practice.git'    
             }
       }
             
        stage('terraform init') {
            steps {
                dir('Day-1') {
                    sh 'terraform init'
                }
            }
        }

        stage('terraform plan') {
            steps {
                dir('Day-1') {
                    sh 'terraform plan'
                }
            }
        }

        stage('terraform apply/destroy') {
            steps {
                dir('Day-1') {
                    sh "terraform ${params.ACTION} -auto-approve"
                }
            }
        }
    }
}


