pipeline {
    agent any

    parameters {
        choice(
            name: 'ACTION',
            choices: ['apply', 'destroy'],
            description: 'Select Terraform action'
        )
    }

    stages {
        stage('Terraform Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/mahimapatel93/Terraform_Practice.git'
            }
        }

        stage('Terraform Init') {
            steps {
                dir('Day-1') {
                    sh 'terraform init'
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                dir('Day-1') {
                    sh 'terraform plan'
                }
            }
        }

        stage('Terraform Apply/Destroy') {
            steps {
                dir('Day-1') {
                    sh "terraform ${params.ACTION} -auto-approve"
                }
            }
        }
    }
}
